const { db } = require('./database');
console.log('Eliminando datos demo...');
const del = s => { try { db.prepare(s).run(); } catch(e) {} };
del("DELETE FROM isp_workflow_tareas WHERE workflow_id IN (SELECT id FROM isp_workflows WHERE descripcion LIKE '%demo%' OR descripcion LIKE '%prueba%')");
del("DELETE FROM isp_workflows WHERE descripcion LIKE '%demo%' OR descripcion LIKE '%prueba%'");
del("DELETE FROM isp_workflow_tipos WHERE nombre LIKE '%Demo%'");
del("DELETE FROM isp_contratos WHERE notas LIKE '%@demo%'");
del("DELETE FROM isp_portabilidades WHERE notas LIKE '%@demo%'");
del("DELETE FROM isp_tarifas WHERE nombre LIKE '%Demo%'");
del("DELETE FROM isp_descuentos WHERE nombre LIKE '%Demo%'");
del("DELETE FROM isp_permanencias WHERE nombre LIKE '%Demo%'");
del("DELETE FROM isp_incidencias WHERE descripcion LIKE '%demo%'");
del("DELETE FROM isp_tareas WHERE titulo LIKE '%demo%'");
del("DELETE FROM isp_caja WHERE descripcion LIKE '%@demo%'");
del("DELETE FROM isp_articulos WHERE notas LIKE '%@demo%'");
del("DELETE FROM isp_nodos WHERE notas LIKE '%@demo%'");
del("DELETE FROM isp_equipos WHERE notas LIKE '%@demo%'");
del("DELETE FROM isp_plantillas WHERE nombre LIKE '%Demo%'");
del("DELETE FROM isp_campanas WHERE nombre LIKE '%Demo%'");
del("DELETE FROM isp_noticias WHERE titulo LIKE '%Demo%'");
del("DELETE FROM isp_eventos WHERE titulo LIKE '%Demo%'");
del("DELETE FROM isp_listados WHERE descripcion LIKE '%@demo%'");
del("DELETE FROM tickets WHERE asunto LIKE '%demo%'");
del("DELETE FROM clients WHERE nombre LIKE '%Demo%'");
console.log('Datos demo eliminados correctamente.');
